export const FIREBASE_KEY = "AIzaSyDediS6jBO6fl0QM9KuAFgJD8OTtG4g-fg";
export const USER_SIGN_UP =
  "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=";
export const USER_SIGN_IN =
  "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=";
export const USER_UPDATE_INFO =
  "https://identitytoolkit.googleapis.com/v1/accounts:update?key=";
export const GET_USER_DATA =
  "https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=";
export const USER_VERIFY_EMAIL =
  "https://identitytoolkit.googleapis.com/v1/accounts:sendOobCode?key=";
